#!/bin/bash
# Welcome to chajr - Css Html And Javascript Ready
# This script builds a simple local environment to develop js, html, and css.
# Please feel free to change it to suit your needs.

mkdir $1
cd $1
mkdir css js
touch css/main.css js/main.js
cat <<'EOF' > index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="css/main.css"/>
  <script defer src="js/main.js"></script>
  <title>Title</title>
</head>
<body>
  
</body>
</html>
EOF